# Generated by Django 5.0 on 2024-02-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('house', models.CharField(max_length=50)),
                ('postalcode', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=10)),
                ('message_to_seller', models.TextField(blank=True)),
            ],
        ),
    ]
