# Generated by Django 5.0 on 2024-02-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
