# Generated by Django 5.0 on 2024-02-17 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_order_data_alter_order_price'),
    ]

    operations = [
      
    ]
